# Font configuration (changes require restart)
font:
  # The size to use.
  size: 12
  # The normal (roman) font face to use.
  normal:
    family: MesloLGS NF
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: MesloLGS NF

    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: MesloLGS NF
    # Style can be specified to pick a specific face.
    style: Italic

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # gruvbox theme
  ## Normal colors
  #normal:
    #black:   '#282828'
    #red:     '#cc241d'
    #green:   '#98971a'
    #yellow:  '#d79921'
    #blue:    '#458588'
    #magenta: '#b16286'
    #cyan:    '#689d6a'
    #white:   '#a89984'

  ## Bright colors
  #bright:
    #black:   '#928374'
    #red:     '#fb4934'
    #green:   '#b8bb26'
    #yellow:  '#fabd2f'
    #blue:    '#83a598'
    #magenta: '#d3869b'
    #cyan:    '#8ec07c'
    #white:   '#ebdbb2'

  # srcery theme
  # Normal colors
  normal:
    black:   '#1C1B19'
    red:     '#EF2F27'
    green:   '#519F50'
    yellow:  '#FBB829'
    blue:    '#2C78BF'
    magenta: '#E02C6D'
    cyan:    '#0AAEB3'
    white:   '#BAA67F'

  # Bright colors
  bright:
    black:   '#918175'
    red:     '#F75341'
    green:   '#98BC37'
    yellow:  '#FED06E'
    blue:    '#68A8E4'
    magenta: '#FF5C8F'
    cyan:    '#2BE4D0'
    white:   '#FCE8C3'

background_opacity: 0.99

cursor:
  style:
    shape: Block
    thickness: 0.5
